### ISSUE TITLE
Release 0.7.2.0

### ISSUE THREAD

**Issue by konsumlamm** [haskell-primitive/primitive-checked#4]
@andrewthad could you please release version 0.7.2.0 (see #2) on Hackage?

**Comment by konsumlamm** [comment]
@andrewthad since you're seemingly not actively maintaining this library (https://github.com/haskell-primitive/primitive-checked/pull/3#issuecomment-903194919), I'd be willing to take over maintainership for it. Maintaining shouldn't be hard, as the API is the same as for `primitive` (by design), so I don't think there's much I could do wrong :)

**Comment by andrewthad** [comment]
Yes, I don’t really use this library myself for anything anymore.
I’ve added you as a maintainer on GitHub. I will add you on hackage as well when I get back to a computer.

**Comment by konsumlamm** [comment]
@andrewthad any update?

**Comment by andrewthad** [comment]
Just added you now on hackage.

**Comment by konsumlamm** [comment]
Thanks, I just uploaded version [0.7.2.0](https://hackage.haskell.org/package/primitive-checked-0.7.2.0).
